### PR TITLE
Try to upgrade cmake on Travis CI

### PR DESCRIPTION
**Pull request by bjorn**
The latest error is:
```
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/cmake.list:1 and /etc/apt/sources.list.d/george-edison55-cmake-3_x-trusty.list:1
```
I do not know where this other `cmake.list` file comes from, but maybe it helps to remove `cmake` from the list of packages

I've also reformatted the `script` part to make the build log less confusing (it printed all commands as one multi-line string, rather than printing each command right before its output).

### CODE REVIEW

**Comment by Modanung** [comment]
Still getting:
```
cmake is already the newest version (3.2.2-2~ubuntu14.04.1~ppa1).
```

**Comment by bjorn** [comment]
This PR was not supposed to be merged while it was still failing... :-)

**Comment by bjorn** [comment]
> cmake is already the newest version (3.2.2-2~ubuntu14.04.1~ppa1).

Now that I [look at the PPA we're adding](https://launchpad.net/~george-edison55/+archive/ubuntu/cmake-3.x?field.series_filter=trusty), it's obvious since for Trusty it only has 3.2.2. Maybe we can find a PPA that actually has a more recent version of cmake...

**Comment by Modanung** [comment]
Whoops... I must admit I had my doubts. :blush:

**Pull request merged**
