### PR TITLE
WIP Fix Travis CI

### PR DESCRIPTION
**Pull request by Kasijjuf**
According to #11, 
> Travis CI build fails because the included cmake version is older then the minimum required by Urho3D.

Looking at the build logs, it appears that the minimum version of cmake
required is 3.2.3. According to https://launchpad.net/ubuntu/+source/cmake
xenial provides version 3.5.1

### CODE REVIEW

**Comment by Kasijjuf** [comment]
Travis CI reports the version of cmake in use is 3.2.2. I have no idea where this version is being pulled into the build.

**Comment by Kasijjuf** [comment]
@RyDroid, It appears you added the original travis.yml file for this project in commit https://github.com/LucKeyProductions/heXon/pull/8/commits/36c73b517f9b65a8e007df90a1a59ebcfeb9f8b2
Can you provide any insight for getting CI working again in this project?

**Comment by Modanung** [comment]
The cause of the build failing is an increased demand by the engine on the required cmake version.
So making it work at this point would seem to require Travis to build cmake. It should be able to deduce how from Urho3D's [.travil.yml](https://github.com/urho3d/Urho3D/blob/master/.travis.yml).

**Comment by bjorn** [comment]
> Travis CI reports the version of cmake in use is 3.2.2. I have no idea where this version is being pulled into the build.

The answer to this is that Travis CI does not actually have a Xenial build environment. They currently only offer [Precise and Trusty](https://docs.travis-ci.com/user/reference/overview/#Virtualization-environments) environments. It's a little strange that it doesn't error out on the `dist: xenial`, but as you can see in the log it's actually just using Trusty.

Adding `george-edison55-cmake-3.x` didn't work because this source was disallowed (not white-listed). You should be able to get around this by using a sudo-enabled image instead (specify `sudo: required`), and then manually running `sudo add-apt-repository --yes` with the right parameter for that repository, followed by `sudo apt-get update -qq` and something like `sudo apt-get -y install cmake` (not sure if that will upgrade, maybe command needs to look different). That should in any case be easier than compiling cmake yourself (though indeed you could copy that part from Urho3D).

**Comment by Modanung** [comment]
Thanks bro, I'll give it a try. :)

**Comment by bjorn** [comment]
Closing this PR since the problem was fixed by #13 and #14.

**Comment by Modanung** [comment]
Awesome

**Pull request closed without merging**
