### PR TITLE
fix compiling with Visual Studio

### PR DESCRIPTION
**Pull request by 1vanK**

### CODE REVIEW

**Comment by 1vanK** [comment]
You can also using engineParameters_["RenderPath"] = "RenderPaths/Deferred.xml"; for improved fps with much count of light sources

**Comment by Modanung** [comment]
Awesome!
And thanks for the tip, will try that.

**Comment by Modanung** [comment]
When I add `engineParameters_["RenderPath"] = "RenderPaths/Deferred.xml";` to MasterControl::Setup there is ghosting of previous frames:
Screenshot showing aforementioned ghosting

**Comment by 1vanK** [comment]
I dont know. I'm using OpenGL and it works normally. Try to send a bugreport. Maybe in the log has any information.

**Comment by Modanung** [comment]
> I'm using OpenGL
Me too

**Comment by 1vanK** [comment]
Or maybe need update videodriver :)

**Comment by Modanung** [comment]
When I use the nVidia drivers instead of XOrg video performance goes up, but my system crashes quite often.

**Pull request merged**
